export { default as Home } from './pages/Home'
export { default as About } from './pages/About'
export { default as Projects } from './pages/Projects'
export { default as Contact } from './pages/Contact'
export { default as Navbar } from './Navbar/Navbar'
